[package]
name = "devconf-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
devconf-ast.path = "../devconf-ast"
devconf-nodes.path = "../devconf-nodes"
devconf-lexer.path = "../devconf-lexer"