[package]
name = "devconf-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
devconf-lexer.path = "../devconf-lexer"
devconf-nodes.path = "../devconf-nodes"
devconf-tychecker.path = "../devconf-tychecker"
ariadne.workspace = true
